#!/usr/bin/env python3
"""
Automatic Card Data and Image Update Script
Updates allCards.json and downloads new card images
"""

import requests
import json
import os
from pathlib import Path

def update_card_data():
    """Update allCards.json from Lorcana API source"""
    print("Updating card data...")
    
    # Try different Lorcana API sources
    api_sources = [
        "https://api.lorcana-api.com/cards/all",
    ]
    
    for api_url in api_sources:
        try:
            print(f"Trying: {api_url}")
            response = requests.get(api_url, timeout=30)
            response.raise_for_status()
            
            card_data = response.json()
            
            # Save to allCards.json
            output_path = "../tools/lorcana-mulligan/data/allCards.json"
            with open(output_path, 'w', encoding='utf-8') as f:
                json.dump(card_data, f, indent=2, ensure_ascii=False)
            
            print(f"SUCCESS: Card data updated successfully from {api_url}")
            return True
            
        except Exception as e:
            print(f"FAILED: Failed to get data from {api_url}: {e}")
            continue
    
    print("FAILED: All API sources failed")
    return False

def update_image_mapping():
    """Update cardImageMap.js based on available images"""
    print("Updating image mappings...")
    
    image_dir = Path("../tools/lorcana-mulligan/card-images")
    card_data_path = "../tools/lorcana-mulligan/data/allCards.json"
    
    # Load card data
    with open(card_data_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # Handle different API response formats
    if isinstance(data, list):
        cards = data  # Direct list of cards
    elif isinstance(data, dict):
        cards = data.get('cards', data.get('data', []))  # Check common keys
    else:
        cards = []
    
    # Create mapping
    image_mapping = {}
    missing_images = []
    
    for card in cards:
        card_name = card.get('Name', '')
        if not card_name:
            continue
            
        # Generate expected filename
        safe_name = sanitize_filename(card_name)
        image_file = f"{safe_name}.jpg"
        image_path = image_dir / image_file
        
        if image_path.exists():
            image_mapping[card_name] = f"card-images/{image_file}"
        else:
            missing_images.append(card_name)
    
    # Generate cardImageMap.js
    output_path = "../tools/lorcana-mulligan/data/cardImageMap.js"
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("// Auto-generated card image mapping\n")
        f.write("// Generated by update_cards.py\n\n")
        f.write("const cardImageMap = {\n")
        
        for card_name, image_path in sorted(image_mapping.items()):
            # Escape quotes in card names
            escaped_name = card_name.replace('\\', '\\\\').replace('"', '\\"')
            f.write(f'  "{escaped_name}": "{image_path}",\n')
        
        f.write("};\n\n")
        f.write("// Export for use in modules\n")
        f.write("if (typeof module !== 'undefined' && module.exports) {\n")
        f.write("  module.exports = cardImageMap;\n")
        f.write("}\n")
    
    print(f"SUCCESS: Image mapping updated: {len(image_mapping)} cards mapped")
    
    if missing_images:
        print(f"WARNING: Missing images for {len(missing_images)} cards:")
        for name in missing_images[:10]:  # Show first 10
            print(f"  - {name}")
        if len(missing_images) > 10:
            print(f"  ... and {len(missing_images) - 10} more")
    
    return missing_images

def sanitize_filename(name):
    """Convert card name to safe filename"""
    replacements = {
        '/': '_', '\\': '_', ':': '_', '*': '_', 
        '?': '_', '"': '_', '<': '_', '>': '_', '|': '_',
        "'": "", '"': '', '!': '', ',': '', '.': '', ' ': '_'
    }
    
    safe_name = name
    for old, new in replacements.items():
        safe_name = safe_name.replace(old, new)
    
    while '__' in safe_name:
        safe_name = safe_name.replace('__', '_')
        
    return safe_name.strip('_').lower()

def main():
    print("Starting card update process...")
    
    # Step 1: Update card data
    if update_card_data():
        print("SUCCESS: Card data updated")
    else:
        print("WARNING: Using existing card data")
    
    # Step 2: Update image mappings
    missing_images = update_image_mapping()
    
    # Step 3: Download missing images
    if missing_images:
        print(f"\n{len(missing_images)} images need to be downloaded")
        print("Run the image download script to get missing images:")
        print("python download_card_images.py")
    else:
        print("SUCCESS: All card images are available")
    
    print("\nUpdate process complete!")

if __name__ == "__main__":
    main()